#!/bin/sh
cd ${0%/*} || exit 1
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

# Recreate empty .foam file for ParaView (cleanCase removes *.foam)
touch mixingPrecipitation.foam

#------------------------------------------------------------------------------
