#!/bin/sh
cd ${0%/*} || exit 1
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication setFields

# Override setFields phase initialization with the saved alpha fields.
cp -f 0.orig/alpha.solid 0.orig/alpha.liquid 0/

runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructPar

# Recreate empty .foam file for ParaView
touch mixingPrecipitation.foam

#------------------------------------------------------------------------------
